variables:
   GIT_SUBMODULE_STRATEGY: recursive
   ORD_SOUMET_W: "10"
   ORD_SOUMET_C: "4"
   ORD_SOUMET_M: "8G"
   ORD_SOUMET_TMPFS: "1G"

.env:
   build:
      - . r.load.dot ${ECCI_PROCESS_SSM}/libs cmd/cmds/ext/20240627 cmd/cmds/ext/20250808 
   variables:
      ALLOW_FAILURE_ARCHS: ""

include:
   - project: 'RPN-SI/ci-admin'
     ref: dev
     file: '/ci/.gitlab-ci-config.yml'
     
deploy:staging:
   stage: deploy
   only:
      - master
      - tags
      - dev
      - schedules
   script:
      - ~/ci-admin-bundle/bin/ci-stage-ssm.sh libs ${CI_PROJECT_NAME} "${CI_COMMIT_TAG}" "${ECCI_PROCESS}"
