variables:
   GIT_SUBMODULE_STRATEGY: recursive
stages:
#   - configure
    - build
    - test
#    - package
#    - deploy
#    - doc

before_script:
   - export CLICOLOR_FORCE=true
   - source ~/ci-admin-bundle/environments/latest/profile.sh

build_gnu-7.4.0:
   stage: build
   artifacts:
      untracked: true
   script:
   script:
      - source ~/ci-admin-bundle/environments/latest/ubuntu-18.04-amd-64/gnu-7.4.0.sh
      - ./makeit -build -reconf 

build_gnu-9.3.0:
   stage: build
   artifacts:
      untracked: true
   script:
   script:
      - source ~/ci-admin-bundle/environments/latest/ubuntu-18.04-amd-64/gnu-9.3.0.sh
      - ./makeit -build -reconf 

build_intel_amd64:
   stage: build
   artifacts:
      untracked: true
   script:
      - source ~/ci-admin-bundle/environments/latest/ubuntu-18.04-amd-64/intel-19.0.3.199.sh
      - ./makeit -build -reconf 

build_intel_skylake:
   stage: build
   artifacts:
      untracked: true
   script:
      - source ~/ci-admin-bundle/environments/latest/ubuntu-18.04-skylake-64/intel-19.0.3.199.sh
      - ./makeit -build -reconf 

test_intel:
   stage: test
   script:
      - source ~/ci-admin-bundle/environments/latest/ubuntu-18.04-amd-64/intel-19.0.3.199.sh
      - export LIBGEOREF_DATA=/space/hall3/sitestore/eccc/cmd/s/nil000/Projects/libgeoref/GRIDS
      - ./makeit -test

test_gnu:
   stage: test
   script:
      - source ~/ci-admin-bundle/environments/latest/ubuntu-18.04-amd-64/gnu-7.4.0.sh
      - ./makeit -test
#ssm:
#   stage: package
#   script:
#      - ./makeit -ssm
