variables:
   GIT_SUBMODULE_STRATEGY: recursive
stages:
    - build
    - test
#    - package
#    - deploy

before_script:
   - export CLICOLOR_FORCE=true

build:intel-19.0.3:
  stage: build
  script:
    - source ci-env/latest/ubuntu-18.04-skylake-64/intel-19.0.3.199.sh
    - mkdir build_intel-19.0.3
    - cd build_intel-19.0.3
    - cmake ../ -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install-dir
    - make
  artifacts:
    expire_in: 2 hrs
    paths:
      - build_intel-19.0.3

build:gnu-7.4.0:
  stage: build
  script:
    - source ci-env/latest/ubuntu-18.04-amd-64/gnu-7.4.0.sh
    - mkdir build_gnu-7.4.0
    - cd build_gnu-7.4.0
    - cmake ../ -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install-dir
    - make
  artifacts:
    expire_in: 2 hrs
    paths:
      - build_gnu-7.4.0

build:gnu-9.3.0:
  stage: build
  script:
    - source ci-env/latest/ubuntu-18.04-amd-64/gnu-9.3.0.sh
    - mkdir build_gnu-9.3.0
    - cd build_gnu-9.3.0
    - cmake ../ -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install-dir
    - make
  artifacts:
    expire_in: 2 hrs
    paths:
      - build_gnu-9.3.0

test:intel-19.0.3:
   stage: test
   script:
      - source ci-env/latest/ubuntu-18.04-amd-64/intel-19.0.3.199.sh
      - make test

test:gnu-7.4.0:
   stage: test
   script:
      - source ~/ci-admin-bundle/environments/latest/ubuntu-18.04-amd-64/gnu-7.4.0.sh
      - make test


